# Generated by Django 4.1.6 on 2023-03-15 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('physical_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('nb', 'non binary')], max_length=20)),
                ('sexuality', models.CharField(choices=[('w', 'like women'), ('m', 'like men'), ('bi', 'like both')], default='bi', max_length=20)),
                ('img1', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures')),
                ('img2', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures')),
                ('img3', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures')),
                ('img4', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures')),
                ('liked', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
                ('likers', models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
